[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
fnv = "1.0.7"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.58"
vts_core = { path = "crates/vts_core" }
